// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using ReceitaCrud.Data;

#nullable disable

namespace ReceitaCrud.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ReceitaCrud.Receitas.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

<<<<<<< HEAD
                    b.Property<double>("CustoAproximado")
                        .HasColumnType("REAL");
=======
                    b.Property<int>("TempoPreparo")
                        .HasColumnType("INTEGER");

                    b.Property<float>("CustoAproximado")
                        .HasColumnType("INTEGER");
>>>>>>> f5854a85d19b8c720d7ebadf35a671d9a0d62260

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

<<<<<<< HEAD
                    b.Property<int>("TempoPreparo")
                        .HasColumnType("INTEGER");

=======
>>>>>>> f5854a85d19b8c720d7ebadf35a671d9a0d62260
                    b.HasKey("Id");

                    b.ToTable("Receitas");
                });
#pragma warning restore 612, 618
        }
    }
<<<<<<< HEAD
}
=======
}
>>>>>>> f5854a85d19b8c720d7ebadf35a671d9a0d62260
